//
// Created by niklas on 02.12.19.
//

#ifndef FUSE_TRY_CONFIG_H
#define FUSE_TRY_CONFIG_H


#define DEFAULT_OPEN_MODUS "r+"
#define SECTOR_SIZE 512
#define EOS32_BLOCK_SIZE 4096
//block size darf NIE 0 sein
#define DEFAULT_ATTR_TIMEOUT 100000000.0
#define DEFAULT_ENTRY_TIMEOUT 100000000.0
#define MAX_INODE_NUMBER UINT32_MAX
#define POINTER_STACK_COUNT 50

#define DEFAULT_ERROR EFAULT
#define DISK_PART_TABLE_BEGIN 512
#define PARTENTRY_SIZE 32

#define LINK_BLOCK_OFFSET_ON_FREEBLOCKLIST_CHAIN_NOT_SUPERBLOCK 4
#define NUMBER_OF_FREE_BLOCK_ADDRESS_ON_FREEBLOCKLIST_CHAIN_NOT_SUPERBLOCK 0
#define FREE_BLOCK_LIST_OFFSET_ON_FREEBLOCKLIST_CHAIN_NOT_SUPERBLOCK 8

#define MAX_BYTES UINT32_MAX

#define FUSE_USE_VERSION 31
#define INODE_OFFSET_BLOCKADDRESS_BEGIN ( 4 * 8)
#define INODE_BLOCKADDRESSES_SIZE (INODE_SIZE - INODE_OFFSET_BLOCKADDRESS_BEGIN)

#endif //FUSE_TRY_CONFIG_H
